# Generated by Django 4.2.7 on 2025-09-15 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('owner', 'Owner'), ('none', 'None')], max_length=20)),
                ('party_id', models.PositiveBigIntegerField()),
                ('entered_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entered_currency', models.CharField(max_length=10)),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='core.transaction')),
            ],
        ),
    ]
