# Generated by Django 4.2.7 on 2025-09-15 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('payment_received', 'Payment Received'), ('payment_made', 'Payment Made'), ('loan_given', 'Loan Given'), ('loan_received', 'Loan Received'), ('loan_repayment_made', 'Loan Repayment Made'), ('loan_repayment_received', 'Loan Repayment Received'), ('expense', 'Expense'), ('withdrawal', 'Withdrawal'), ('owner_deposit', 'Owner Deposit'), ('return_sale', 'Return Sale'), ('return_purchase', 'Return Purchase'), ('refund', 'Refund'), ('sale_adjustment', 'Sale Adjustment'), ('purchase_adjustment', 'Purchase Adjustment'), ('misc', 'Miscellaneous')], max_length=30)),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('owner', 'Owner'), ('none', 'None')], default='none', max_length=20)),
                ('party_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('entered_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entered_currency', models.CharField(max_length=10)),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
